-- ============================================================================
--  « LES CARNETS » — Schéma du Carnet de recettes (données) dans le projet
--  commun. À exécuter dans le projet Supabase « Les Carnets ».
-- ----------------------------------------------------------------------------
--  `profiles` et `subscriptions` sont déjà là (partagés, migration 0001) :
--  on ne recrée QUE les tables de données propres à Recettes.
--
--  Les colonnes `id` en bigint sont des identités « by default » : on pourra
--  insérer des id explicites pendant la migration des données, puis on
--  recalera la séquence.
-- ============================================================================

-- ---- recipes ---------------------------------------------------------------
create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  title text not null,
  category text not null,
  difficulty text not null,
  prep_time integer not null default 0,
  cook_time integer not null default 0,
  servings integer not null default 1,
  description text not null default '',
  image text not null default '🍽️',
  image_url text,
  tags text[] not null default '{}',
  ingredients jsonb not null default '[]',
  steps jsonb not null default '[]',
  related_recipe_ids bigint[] not null default '{}',
  created_at timestamptz not null default now()
);

-- ---- recipe_reviews --------------------------------------------------------
create table if not exists public.recipe_reviews (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipes (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  rating integer not null,
  comment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---- recipe_review_likes ---------------------------------------------------
create table if not exists public.recipe_review_likes (
  id bigint generated by default as identity primary key,
  review_id bigint not null references public.recipe_reviews (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (review_id, user_id)
);

-- ---- recipe_review_replies -------------------------------------------------
create table if not exists public.recipe_review_replies (
  id bigint generated by default as identity primary key,
  review_id bigint not null references public.recipe_reviews (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---- favorites -------------------------------------------------------------
create table if not exists public.favorites (
  user_id uuid not null references auth.users (id) on delete cascade,
  recipe_id bigint not null references public.recipes (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, recipe_id)
);

-- ---- shopping_list_items ---------------------------------------------------
create table if not exists public.shopping_list_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  recipe_id bigint references public.recipes (id) on delete set null,
  text text not null,
  checked boolean not null default false,
  created_at timestamptz not null default now()
);

-- ---- site_ideas ------------------------------------------------------------
create table if not exists public.site_ideas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  title text not null,
  message text not null,
  category text not null default 'amelioration',
  status text not null default 'nouvelle',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---- user_follows ----------------------------------------------------------
create table if not exists public.user_follows (
  id uuid primary key default gen_random_uuid(),
  follower_id uuid not null references auth.users (id) on delete cascade,
  following_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (follower_id, following_id)
);

-- ============================================================================
--  RLS — mêmes règles que sur l'ancien Recettes (+ droits admin de 0005).
-- ============================================================================

alter table public.recipes enable row level security;
drop policy if exists recipes_select on public.recipes;
create policy recipes_select on public.recipes for select using (true);
drop policy if exists recipes_insert on public.recipes;
create policy recipes_insert on public.recipes for insert with check (auth.uid() = user_id);
drop policy if exists recipes_update on public.recipes;
create policy recipes_update on public.recipes for update using (auth.uid() = user_id or public.is_admin()) with check (auth.uid() = user_id or public.is_admin());
drop policy if exists recipes_delete on public.recipes;
create policy recipes_delete on public.recipes for delete using (auth.uid() = user_id or public.is_admin());

alter table public.recipe_reviews enable row level security;
drop policy if exists recipe_reviews_select on public.recipe_reviews;
create policy recipe_reviews_select on public.recipe_reviews for select using (true);
drop policy if exists recipe_reviews_insert on public.recipe_reviews;
create policy recipe_reviews_insert on public.recipe_reviews for insert with check (auth.uid() = user_id);
drop policy if exists recipe_reviews_update on public.recipe_reviews;
create policy recipe_reviews_update on public.recipe_reviews for update using (auth.uid() = user_id or public.is_admin()) with check (auth.uid() = user_id or public.is_admin());
drop policy if exists recipe_reviews_delete on public.recipe_reviews;
create policy recipe_reviews_delete on public.recipe_reviews for delete using (auth.uid() = user_id or public.is_admin());

alter table public.recipe_review_likes enable row level security;
drop policy if exists recipe_review_likes_select on public.recipe_review_likes;
create policy recipe_review_likes_select on public.recipe_review_likes for select using (true);
drop policy if exists recipe_review_likes_insert on public.recipe_review_likes;
create policy recipe_review_likes_insert on public.recipe_review_likes for insert with check (auth.uid() = user_id);
drop policy if exists recipe_review_likes_delete on public.recipe_review_likes;
create policy recipe_review_likes_delete on public.recipe_review_likes for delete using (auth.uid() = user_id or public.is_admin());

alter table public.recipe_review_replies enable row level security;
drop policy if exists recipe_review_replies_select on public.recipe_review_replies;
create policy recipe_review_replies_select on public.recipe_review_replies for select using (true);
drop policy if exists recipe_review_replies_insert on public.recipe_review_replies;
create policy recipe_review_replies_insert on public.recipe_review_replies for insert with check (auth.uid() = user_id);
drop policy if exists recipe_review_replies_update on public.recipe_review_replies;
create policy recipe_review_replies_update on public.recipe_review_replies for update using (auth.uid() = user_id or public.is_admin()) with check (auth.uid() = user_id or public.is_admin());
drop policy if exists recipe_review_replies_delete on public.recipe_review_replies;
create policy recipe_review_replies_delete on public.recipe_review_replies for delete using (auth.uid() = user_id or public.is_admin());

alter table public.favorites enable row level security;
drop policy if exists favorites_select on public.favorites;
create policy favorites_select on public.favorites for select using (auth.uid() = user_id or public.is_admin());
drop policy if exists favorites_insert on public.favorites;
create policy favorites_insert on public.favorites for insert with check (auth.uid() = user_id);
drop policy if exists favorites_delete on public.favorites;
create policy favorites_delete on public.favorites for delete using (auth.uid() = user_id or public.is_admin());

alter table public.shopping_list_items enable row level security;
drop policy if exists shopping_list_items_all on public.shopping_list_items;
create policy shopping_list_items_all on public.shopping_list_items for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists shopping_list_items_admin on public.shopping_list_items;
create policy shopping_list_items_admin on public.shopping_list_items for all using (public.is_admin()) with check (public.is_admin());

alter table public.site_ideas enable row level security;
drop policy if exists site_ideas_select on public.site_ideas;
create policy site_ideas_select on public.site_ideas for select using (auth.uid() = user_id or public.is_admin());
drop policy if exists site_ideas_insert on public.site_ideas;
create policy site_ideas_insert on public.site_ideas for insert with check (auth.uid() = user_id);
drop policy if exists site_ideas_update_admin on public.site_ideas;
create policy site_ideas_update_admin on public.site_ideas for update using (public.is_admin()) with check (public.is_admin());
drop policy if exists site_ideas_delete on public.site_ideas;
create policy site_ideas_delete on public.site_ideas for delete using (auth.uid() = user_id or public.is_admin());

alter table public.user_follows enable row level security;
drop policy if exists user_follows_select on public.user_follows;
create policy user_follows_select on public.user_follows for select using (true);
drop policy if exists user_follows_insert on public.user_follows;
create policy user_follows_insert on public.user_follows for insert with check (auth.uid() = follower_id);
drop policy if exists user_follows_delete on public.user_follows;
create policy user_follows_delete on public.user_follows for delete using (auth.uid() = follower_id or public.is_admin());
